// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkgpxtnjfbhlhaopehld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrZ3B4dG5qZmJobGhhb3BlaGxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2NDM1MzksImV4cCI6MjA1NTIxOTUzOX0.9rULXgQ3rMl_qTAliVxMw9JKskhaxaZW9sdR9BMplLI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);